version : "3"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    
  app:
    build: .
    ports:
      - 3030:3030
    environment:
      App_PORT: 8000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}